# Домашнє завдання: Внесення оновлень в БД і робота з транзакціями

Це ДЗ передбачене під виконання на локальній машині. Виконання з Google Colab буде суттєво ускладнене.

## Підготовка
1. Переконайтесь, що у вас встановлены необхідні бібліотеки:
   ```bash
   pip install sqlalchemy pymysql pandas matplotlib seaborn python-dotenv
   ```

2. Створіть файл `.env` з параметрами підключення до бази даних classicmodels. Базу даних ви можете отримати через

  - docker-контейнер згідно існтрукції в [документі](https://www.notion.so/hannapylieva/Docker-1eb94835849480c9b2e7f5dc22ee4df9), також відео інструкції присутні на платформі - уроки "MySQL бази, клієнт для роботи з БД, Docker і ChatGPT для запитів" та "Як встановити Docker для роботи з базами даних без терміналу"
  - або встановивши локально цю БД - для цього перегляньте урок "Опціонально. Встановлення MySQL та  БД Сlassicmodels локально".
  
  Приклад `.env` файлу ми створювали в лекції. Ось його обовʼязкове наповнення:
    ```
    DB_HOST=your_host
    DB_PORT=3306 або 3307 - той, який Ви налаштували
    DB_USER=your_username
    DB_PASSWORD=your_password
    DB_NAME=classicmodels
    ```
  Якщо ви створили цей файл під час перегляду лекції - **новий створювати не треба**. Замініть лише назву БД, або пропишіть назву в коді створення підключення (замість отримання назви цільової БД зі змінних оточення). Але переконайтесь, що до `.env` файл лежить в тій самій папці, що і цей ноутбук.

  **УВАГА!** НЕ копіюйте скрит для **створення** `.env` файлу. В лекції він наводиться для прикладу. І давалось пояснення, що в реальних проєктах ми НІКОЛИ не пишемо доступи до бази в коді. Копіювання скрипта для створення `.env` файлу сюди в ДЗ буде вважатись грубою помилкою і ми зніматимемо бали.

3. Налаштуйте підключення через SQLAlchemy до БД за прикладом в лекції.

Рекомендую вивести (відобразити) змінну engine після створення. Вона має бути не None! Якщо None - значить у Вас не підтягнулись налаштування з .env файла.

Ви також можете налаштувати параметри підключення до БД без .env файла, просто прописавши текстом в відповідних місцях. Це - не рекомендований підхід.


## Завдання

### Завдання 1: Оновлення інформації про клієнта (2 бали)

**Створіть функцію для оновлення контактної інформації клієнта за його номером** з наступними можливостями:
- Оновлення телефону клієнта
- Оновлення email (якщо поле існує в таблиці)

Опціонально, якщо вам хочеться більше практики:
- Логування змін в окрему таблицю

Використайте підхід з параметризованими запитами через `text()` та `UPDATE` оператор. Не забудьте на початку перевірити чи існує клієнт з таким номером в базі - це хороша практика.

Отримати всі колонки, які існують в таблиці ви можете наступним запитом
```
  SELECT COLUMN_NAME, DATA_TYPE
  FROM INFORMATION_SCHEMA.COLUMNS
  WHERE TABLE_NAME = 'customers'
```

Запустіть функцію і продемонструйте її роботу, запустивши SELECT, який допоможе це зробити.

In [1]:
!pip install sqlalchemy pymysql openpyxl requests python-dotenv --quiet

from datetime import datetime, timedelta
import os

from dotenv import load_dotenv
import pandas as pd
import sqlalchemy as sa
from sqlalchemy import create_engine, text, MetaData, Table
from sqlalchemy.orm import sessionmaker

In [3]:
def create_connection():
    """
    Створює підключення через SQLAlchemy
    """
    # Завантажуємо змінні середовища
    load_dotenv()

    # Отримуємо параметри з environment variables
    host = os.getenv('DB_HOST', 'localhost')
    port = os.getenv('DB_PORT', '3306')
    user = os.getenv('DB_USER')
    password = os.getenv('DB_PASSWORD')
    database = os.getenv('DB_NAME')

    if not all([user, password, database]):
        raise ValueError("Не всі параметри БД задані в .env файлі!")

    # Створюємо connection string
    connection_string = f"mysql+pymysql://{user}:{password}@{host}:{port}/{database}"

    # Створюємо engine з connection pooling
    engine = create_engine(
        connection_string,
        pool_size=2,           # Розмір пулу підключень
        max_overflow=20,        # Максимальна кількість додаткових підключень
        pool_pre_ping=True,     # Перевірка підключення перед використанням
        echo=False              # Логування SQL запитів (True для debug)
    )

    # Тестуємо підключення
    try:
        with engine.connect() as conn:
            result = conn.execute(text("SELECT 1"))
            result.fetchone()

        print("✅ Підключення до БД успішне!")
        print(f"🔗 {user}@{host}:{port}/{database}")
        print(f"⚡ Engine: {engine}")

        return engine

    except Exception as e:
        print(f"❌ Помилка підключення: {e}")
        return None

# Створюємо підключення
engine = create_connection()

✅ Підключення до БД успішне!
🔗 root@127.0.0.1:3307/employees
⚡ Engine: Engine(mysql+pymysql://root:***@127.0.0.1:3307/employees)

In [7]:
def update_customer_contacts(engine, customer_id, new_phone=None, new_email=None):
    """
    Оновлює телефон та/або email клієнта за його customerNumber, явно використовуючи схему classicmodels.
    """
    # Крок 1: Динамічно отримуємо колонки, які реально існують в таблиці 'customers'
    columns_query = text("""
        SELECT COLUMN_NAME 
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_NAME = 'customers' AND TABLE_SCHEMA = 'classicmodels';
    """)
    
    with engine.connect() as conn:
        result = conn.execute(columns_query)
        existing_columns = [row[0] for row in result.fetchall()]
    
    # Крок 2: Перевіряємо, чи існує клієнт з таким номером в базі classicmodels
    check_user_query = text("""
        SELECT customerName FROM classicmodels.customers WHERE customerNumber = :cust_id;
    """)
    
    with engine.connect() as conn:
        user_res = conn.execute(check_user_query, {"cust_id": customer_id}).fetchone()
        
    if not user_res:
        print(f"❌ Клієнта з номером {customer_id} не знайдено в базі даних classicmodels.")
        return False
    
    customer_name = user_res[0]
    print(f"🔍 Знайдено клієнта: '{customer_name}' (ID: {customer_id})")
    
    # Крок 3: Формуємо списки для UPDATE залежно від наявних колонок
    update_fields = []
    params = {"cust_id": customer_id}
    
    if new_phone and 'phone' in existing_columns:
        update_fields.append("phone = :new_phone")
        params["new_phone"] = new_phone
            
    if new_email and 'email' in existing_columns:
        update_fields.append("email = :new_email")
        params["new_email"] = new_email
            
    if not update_fields:
        print("ℹ️ Немає даних для оновлення або вказані колонки відсутні в таблиці.")
        return False
    
    # Крок 4: Виконуємо параметризований UPDATE запит із префіксом схеми
    sql_update = text(f"""
        UPDATE classicmodels.customers 
        SET {', '.join(update_fields)} 
        WHERE customerNumber = :cust_id;
    """)
    
    with engine.begin() as conn:  
        conn.execute(sql_update, params)
        print(f"✅ Контактні дані для '{customer_name}' успішно оновлено!")
            
    return True

In [9]:
# Вибираємо ID клієнта для тесту
test_customer_id = 103

print("--- СТАН ДО ОНОВЛЕННЯ ---")
df_before = pd.read_sql(
    text("SELECT customerNumber, customerName, phone FROM classicmodels.customers WHERE customerNumber = :id"),
    engine, params={"id": test_customer_id}
)
display(df_before)

print("\n--- ЗАПУСК ФУНКЦІЇ ОНОВЛЕННЯ ---")
# Оновлюємо телефон
update_customer_contacts(engine, customer_id=test_customer_id, new_phone="+380 (97) 123-4567")

print("\n--- СТАН ПІСЛЯ ОНОВЛЕННЯ (ПЕРЕВІРОЧНИЙ SELECT) ---")
df_after = pd.read_sql(
    text("SELECT customerNumber, customerName, phone FROM classicmodels.customers WHERE customerNumber = :id"),
    engine, params={"id": test_customer_id}
)
display(df_after)

--- СТАН ДО ОНОВЛЕННЯ ---

   customerNumber       customerName               phone
0             103  Atelier graphique  +380 (97) 123-4567

--- ЗАПУСК ФУНКЦІЇ ОНОВЛЕННЯ ---
🔍 Знайдено клієнта: 'Atelier graphique' (ID: 103)
✅ Контактні дані для 'Atelier graphique' успішно оновлено!

--- СТАН ПІСЛЯ ОНОВЛЕННЯ (ПЕРЕВІРОЧНИЙ SELECT) ---

   customerNumber       customerName               phone
0             103  Atelier graphique  +380 (97) 123-4567

### Завдання 2: Створення нового замовлення з транзакцією (5 балів)

**Реалізуйте процес створення нового замовлення** з наступними кроками в одній транзакції:
- Створення запису в таблиці `orders`
- Додавання товарних позицій в `orderdetails`
- Перевірка наявності товарів на складі
- Зменшення кількості товарів на складі

Запустіть процес з тестовими даними і продемонструйте через SELECT, що процес успішно відпрацював і були виконані необхідні операції.

In [11]:
def create_new_order(engine, customer_id, order_items):
    """
    Проводить транзакційне створення замовлення:
    1. Перевіряє залишки для всіх товарів.
    2. Створює запис в orders.
    3. Додає позиції в orderdetails.
    4. Зменшує кількість товарів у products.
    
    order_items: список словників [{'productCode': '...', 'quantity': int, 'priceEach': float}]
    """
    
    with engine.begin() as conn: # Початок єдиної транзакції (Auto-COMMIT / Auto-ROLLBACK)
        
        # КРОК 1: Перевірка наявності товарів на складі
        print("🔍 Крок 1: Перевірка залишків на складі...")
        for item in order_items:
            check_stock_sql = text("""
                SELECT quantityInStock, productName 
                FROM classicmodels.products 
                WHERE productCode = :prod_code;
            """)
            stock_res = conn.execute(check_stock_sql, {"prod_code": item['productCode']}).fetchone()
            
            if not stock_res:
                raise ValueError(f"❌ Помилка: Товар з кодом {item['productCode']} не знайдено в базі!")
            
            current_stock, prod_name = stock_res
            if current_stock < item['quantity']:
                raise ValueError(f"❌ Помилка: Недостатньо товару '{prod_name}' на складі! "
                                 f"Запитувано: {item['quantity']}, в наявності: {current_stock}")
            
            print(f"   • Товар '{prod_name}' є в наявності (Склад: {current_stock} шт., Замовлено: {item['quantity']} шт.)")

        # КРОК 2: Створення запису в таблиці orders
        print("\n📝 Крок 2: Створення запису в таблиці orders...")
        
        # Генеруємо новий унікальний orderNumber (беремо максимальний + 1)
        next_order_num_sql = text("SELECT MAX(orderNumber) + 1 FROM classicmodels.orders;")
        new_order_number = conn.execute(next_order_num_sql).scalar()
        
        insert_order_sql = text("""
            INSERT INTO classicmodels.orders (orderNumber, orderDate, requiredDate, status, customerNumber)
            VALUES (:order_num, :order_date, :req_date, 'In Process', :cust_id);
        """)
        
        # Визначаємо дати (замовлення — сьогодні, виконати — через 7 днів)
        today = datetime.now().strftime('%Y-%m-%d')
        required_date = (datetime.now().replace(day=datetime.now().day + 7)).strftime('%Y-%m-%d')
        
        conn.execute(insert_order_sql, {
            "order_num": new_order_number,
            "order_date": today,
            "req_date": required_date,
            "cust_id": customer_id
        })
        print(f"   • Створено замовлення №{new_order_number}")

        # КРОК 3 & 4: Додавання в orderdetails та Зменшення кількості на складі
        print("\n📦 Кроки 3 та 4: Додавання позицій та списання зі складу...")
        
        insert_details_sql = text("""
            INSERT INTO classicmodels.orderdetails (orderNumber, productCode, quantityOrdered, priceEach, orderLineNumber)
            VALUES (:order_num, :prod_code, :qty, :price, :line_num);
        """)
        
        update_stock_sql = text("""
            UPDATE classicmodels.products 
            SET quantityInStock = quantityInStock - :qty 
            WHERE productCode = :prod_code;
        """)
        
        for idx, item in enumerate(order_items, start=1):
            # Запис деталей
            conn.execute(insert_details_sql, {
                "order_num": new_order_number,
                "prod_code": item['productCode'],
                "qty": item['quantity'],
                "price": item['priceEach'],
                "line_num": idx
            })
            
            # Списання зі складу
            conn.execute(update_stock_sql, {
                "qty": item['quantity'],
                "prod_code": item['productCode']
            })
            print(f"   • Позицію {item['productCode']} додано. Склад оновлено (-{item['quantity']} шт.)")
            
        print(f"\n🎉 Транзакція успішна! Замовлення №{new_order_number} повністю оформлено.")
        return new_order_number

In [13]:
# Тестові дані: Клієнт 103 купує дві моделі машинок
test_customer_id = 103
test_cart = [
    {"productCode": "S10_1678", "quantity": 5, "priceEach": 48.81}, # 1969 Harley Davidson Ultimate Chopper
    {"productCode": "S10_1949", "quantity": 3, "priceEach": 98.30}  # 1952 Alpine Renault 1600s
]

print("=================== СТАН СКЛАДУ ДО ТРАНЗАКЦІЇ ===================")
prod_codes = [item['productCode'] for item in test_cart]
df_stock_before = pd.read_sql(
    text("SELECT productCode, productName, quantityInStock FROM classicmodels.products WHERE productCode IN :codes"),
    engine, params={"codes": tuple(prod_codes)}
)
display(df_stock_before)


print("\n=================== ЗАПУСК ТРАНЗАКЦІЇ ===================")
try:
    created_id = create_new_order(engine, customer_id=test_customer_id, order_items=test_cart)
except Exception as e:
    print(e)
    created_id = None


if created_id:
    print("\n=================== ПЕРЕВІРКА РЕЗУЛЬТАТІВ (SELECT) ===================")
    
    print(f"1. Перевірка створення голови замовлення №{created_id} в orders:")
    df_order = pd.read_sql(
        text("SELECT * FROM classicmodels.orders WHERE orderNumber = :num"),
        engine, params={"num": created_id}
    )
    display(df_order)
    
    print(f"\n2. Перевірка товарних позицій у таблиці orderdetails:")
    df_details = pd.read_sql(
        text("SELECT * FROM classicmodels.orderdetails WHERE orderNumber = :num"),
        engine, params={"num": created_id}
    )
    display(df_details)
    
    print("\n3. Перевірка фінального стану складу (кількість мала зменшитись):")
    df_stock_after = pd.read_sql(
        text("SELECT productCode, productName, quantityInStock FROM classicmodels.products WHERE productCode IN :codes"),
        engine, params={"codes": tuple(prod_codes)}
    )
    display(df_stock_after)

=================== СТАН СКЛАДУ ДО ТРАНЗАКЦІЇ ===================

  productCode                            productName  quantityInStock
0    S10_1678  1969 Harley Davidson Ultimate Chopper             7933
1    S10_1949               1952 Alpine Renault 1300             7305

=================== ЗАПУСК ТРАНЗАКЦІЇ ===================
🔍 Крок 1: Перевірка залишків на складі...
   • Товар '1969 Harley Davidson Ultimate Chopper' є в наявності (Склад: 7933 шт., Замовлено: 5 шт.)
   • Товар '1952 Alpine Renault 1300' є в наявності (Склад: 7305 шт., Замовлено: 3 шт.)

📝 Крок 2: Створення запису в таблиці orders...
day is out of range for month